### ISSUE TITLE
can't access the management plugin interface

### ISSUE THREAD

**Issue by hamidasgarian** [ypereirareis/docker-rabbitmq-ha-cluster#3]
i follow in instructions and when i run make state get this output:

WARNING: The UID variable is not set. Defaulting to a blank string
rmq_haproxy_1         up
rmq_rmq1_1             up
rmq_rmq2_1             up
rmq_rmq3_1             up

but can't access the management plugin interface on browser on:
http://my-local-ip:1234
http://my-local-ip:1235
http://my-local-ip:1236

i think the problem might be on running container section. when i get docker ps i see the containers are up in 127.0.0.1:1236 form but correct form is 0.0.0.0:1234

**Comment by ypereirareis** [comment]
Hi.

The warning is not really important. To access the admin interface you need to use the correct IP address indeed. If 127.0.0.1 is not suitable for you change it in the docker compose file.

Bye.

**Comment by hamidasgarian** [comment]
tnx a lot
 i change 127.0.0.1 in docker compose to my external ip and works fine!

now i have another question, i want to config my producer to listen to the port 12000 some ip address add save the recived packets to rabbit. what should i write in produce.sh ?

i know its not directly relevant to this project but i very appreciated if anyone can help me

**Comment by ypereirareis** [comment]
Sorry but I dont understand your question. A producer does not listen to anything...

**Comment by hamidasgarian** [comment]
i`m receiving packets at port 12000 my server. i want to HA listen to the port and saving packets to rabbit in a queue. for do that how i configured my producer and ha?

**Comment by ypereirareis** [comment]
Oh actually I think you do not really understand what the project is for. And what is a message broker. It's the producer that sends data to rabbitmq. Or you can add data yourself in rabbitmq directly or through haproxy.

**Comment by ypereirareis** [comment]
This issue is not really an issue
