### ISSUE TITLE
ERROR: for composer  Cannot create container for service composer: b'No command specified'

### ISSUE THREAD

**Issue by flik** [ypereirareis/docker-rabbitmq-ha-cluster#4]
These issues are coming:

docker-compose up -d
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

docker-rabbitmq-ha-cluster_rmq2_1 is up-to-date
docker-rabbitmq-ha-cluster_rmq1_1 is up-to-date
Starting docker-rabbitmq-ha-cluster_php_1 ... 
docker-rabbitmq-ha-cluster_rmq3_1 is up-to-date
docker-rabbitmq-ha-cluster_rmqN_1 is up-to-date
docker-rabbitmq-ha-cluster_haproxy_1 is up-to-date
Creating docker-rabbitmq-ha-cluster_composer_1 ... error
Starting docker-rabbitmq-ha-cluster_php_1      ... error
ERROR: for docker-rabbitmq-ha-cluster_composer_1  Cannot create container for service composer: b'No command specified'

ERROR: for docker-rabbitmq-ha-cluster_php_1  Cannot start service php: b'OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/Users/dockers/docker-rabbitmq-ha-cluster/var/logs/app\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/a67364c03e8da196a3b89f07a6be4c57761b00216d0c975480a64bdfd566f0cd/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/a67364c03e8da196a3b89f07a6be4c57761b00216d0c975480a64bdfd566f0cd/merged/var/www/html/var/logs\\\\\\" caused \\\\\\"mkdir /var/lib/docker/overlay2/a67364c03e8da196a3b89f07a6be4c57761b00216d0c975480a64bdfd566f0cd/merged/var/www/html/var: permission denied\\\\\\"\\"": unknown'

ERROR: for composer  Cannot create container for service composer: b'No command specified'

ERROR: for php  Cannot start service php: b'OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/Users/dockers/docker-rabbitmq-ha-cluster/var/logs/app\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/a67364c03e8da196a3b89f07a6be4c57761b00216d0c975480a64bdfd566f0cd/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/a67364c03e8da196a3b89f07a6be4c57761b00216d0c975480a64bdfd566f0cd/merged/var/www/html/var/logs\\\\\\" caused \\\\\\"mkdir /var/lib/docker/overlay2/a67364c03e8da196a3b89f07a6be4c57761b00216d0c975480a64bdfd566f0cd/merged/var/www/html/var: permission denied\\\\\\"\\"": unknown'
ERROR: Encountered errors while bringing up the project.

**Comment by ypereirareis** [comment]
Hello ! And goodbye ! 

https://www.wikihow.com/Be-Polite-to-Everyone

**Comment by flik** [comment]
:) I appreciate your whole effort... I just pasted few issues may I was missing some steps. 
I have Mac Pro and docker and docker compose installed.

**Comment by ypereirareis** [comment]
Hello !

```WARNING: The Docker Engine you're using is running in swarm mode.``` 

The project is not swarm compatible so far and not ready for production.

But feel free to send a PR :)
